
# FViT-S3 - Nucleus
seed: 100
last_layer: 'encoder.head'
num_samples: 100
num_runs: 10
batch_size: 32
iid_split: test_out_compound
ood_split: test_out_all_
model_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/featurisation/batch_generalisation/10_plates/
controls_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/'
eval_data_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/10_plates/'
eval_data_file_name: linear_probing
num_epochs: 100
log_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/10_plates/lightning_logs/'
metrics_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/10_plates/
patience: 25
model_name: mae
plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/'



control_ids: ['2022_033924',
    '2022_085227',
    '2022_037716',
    '2022_025848',
    '2022_046054',
    '2022_035095',
    '2022_064022',
    '2022_050797',
    '2022_012818']


comparison_model_name: 1 Plates


batch_generalisation_test_metric_dirs:
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/1_plates/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/5_plates/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/10_plates/test_metrics_mae.pkl


batch_generalisation_test_out_metric_dirs:
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/1_plates/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/5_plates/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/10_plates/test_out_metrics_mae.pkl

batch_generalisation_model_names: 
- 1 Plate
- 5 Plates
- 10 Plates

batch_generalisation_plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/batch_generalisation/'