plates_to_concat: 
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/training/squelette/fvit_s3/20241206050002302230/FEATURES/metadata_features_model0.csv
paths_to_controls: 
 - /hpc/scratch/hdd3/jz601442/datasets/squelette/2021-06/hk539925/ELN27012/control_csvs/G212LFH-M2.csv
 - /hpc/scratch/hdd3/jz601442/datasets/squelette/2021-06/hk539925/ELN27012/control_csvs/G212LFN-M1.csv
plate_barcodes:
 - ELN27012_G212LFH
 - ELN27012_G212LFN
id_barcodes: 
 - ELN27012_G212LFH
 - ELN27012_G212LFN
m2_barcodes: 
 - ELN27012_G212LFI
 - ELN27012_G212LFH
save_path: /hpc/mydata/upt/cjh86475/channel_agnostic_model/finetuning/channel_integration/feedthrough
last_layer: head.module
plot_compounds: 
 - pos-M1
 - neg
 - pos-M2
vmin: 0
vmax: 1.0