
# FViT-S3 - Nucleus
seed: 100
last_layer: 'encoder.head'
num_samples: 100
num_runs: 10
batch_size: 32
iid_split: test_out_compound
ood_split: test_out_all_
model_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/featurisation/actin/
controls_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/'
eval_data_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/'
eval_data_file_name: linear_probing
num_epochs: 100
log_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/lightning_logs/'
metrics_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/
patience: 25
model_name: mae
plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/'




# control_ids: 


control_ids: ['2022_033924',
    '2022_085227',
    '2022_037716',
    '2022_025848',
    '2022_046054',
    '2022_035095',
    '2022_064022',
    '2022_050797',
    '2022_012818']


test_metric_dirs:
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/foundation_vit/test_metrics_foundation_vit.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/resnet18_imagenet2/test_metrics_resnet_imagenet.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/test_metrics_dino_vits8_imagenet.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae/test_metrics_mae.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_no_channel/test_metrics_mae.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_no_batch_avg/test_metrics_mae.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_no_channel_embeds_both/test_metrics_mae.pkl'
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_sample_avg_decoder_only/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_sample_avg_decoder_only_2/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_only/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/actin/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/mitochondria/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_actin/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_mitochondria/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/test_metrics_dino_vits8_imagenet.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/test_metrics_dinov2_vitl14.pkl

test_out_metric_dirs:
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/foundation_vit/test_out_metrics_foundation_vit.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/resnet18_imagenet2/test_out_metrics_resnet_imagenet.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/test_out_metrics_dino_vits8_imagenet.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae/test_out_metrics_mae.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_no_channel/test_out_metrics_mae.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_no_batch_avg/test_out_metrics_mae.pkl'
# - '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_no_channel_embeds_both/test_out_metrics_mae.pkl'
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_sample_avg_decoder_only/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_sample_avg_decoder_only_2/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_only/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/actin/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/mitochondria/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_actin/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_mitochondria/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/test_out_metrics_dino_vits8_imagenet.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/test_out_metrics_dinov2_vitl14.pkl

model_names: 
# - 'FViT'
# - 'ImageNet'
- 'MAE'
- 'DinoViT-S8'
- 'DinoViT-L14'
# - 'Chn. Emb. Decdr. Only'
# - 'No Batch Avg'
# - No Chn. Emb.
# - Smpl. Avg. Dec.
# - Smpl. Avg. Dec.2
# - Nu 
# - Ac
# - M
# - Nu, Ac 
# - Nu, M
# - Nu, M, Ac

comparison_model_name: 'MAE'

batch_generalisation_test_metric_dirs:
- /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/1_plates/test_metrics_mae.pkl
- /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/5_plates/test_metrics_mae.pkl
- /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/10_plates/test_metrics_mae.pkl


batch_generalisation_test_out_metric_dirs:
- /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/1_plates/test_out_metrics_mae.pkl
- /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/5_plates/test_out_metrics_mae.pkl
- /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/10_plates/test_out_metrics_mae.pkl

batch_generalisation_model_names: 
- 1 Plate
- 5 Plates
- 10 Plates

batch_generalisation_plot_save_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/mae_vs_plates/'



channel_integration_test_metric_dirs:
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_only/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/actin/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/mitochondria/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_actin/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_mitochondria/test_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/mitochondria/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_actin/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/test_metrics_mae.pkl



channel_integration_test_out_metric_dirs:
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_only/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/actin/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/mitochondria/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_actin/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/nucleus_mitochondria/test_out_metrics_mae.pkl
# - /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/mitochondria/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_actin/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/test_out_metrics_mae.pkl

channel_integration_model_names: 
- Nu 
- Ac
- M
- Nu, Ac 
- Nu, M
- Nu, M, Ac
channel_integration_comparison_model_name: Nu, M, Ac
channel_integration_plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/'