
channel_integration_test_metric_dirs:
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/mitochondria/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_actin/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/test_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/test_metrics_mae.pkl


channel_integration_test_out_metric_dirs:
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/actin/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/mitochondria/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_actin/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/test_out_metrics_mae.pkl
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/test_out_metrics_mae.pkl

channel_integration_model_names: 
- Nu 
- Ac
- M
- Nu, Ac 
- Nu, M
- Nu, M, Ac
channel_integration_comparison_model_name: Nu, M, Ac
channel_integration_plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/'