paths_to_plates: 
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/training/squelette/fvit_s3/20241205130327485955/FEATURES/metadata_features_model0.csv
- /hpc/scratch/weka01/cjh86475/channel_agnostic_model/training/squelette/fvit_s3/20241206050002302230/FEATURES/metadata_features_model0.csv
paths_to_controls: 
 - /hpc/scratch/hdd3/jz601442/datasets/squelette/2021-06/hk539925/ELN27012/control_csvs/G212LFI-M2.csv
 - /hpc/scratch/hdd3/jz601442/datasets/squelette/2021-06/hk539925/ELN27012/control_csvs/G212LFO-M1.csv
 - /hpc/scratch/hdd3/jz601442/datasets/squelette/2021-06/hk539925/ELN27012/control_csvs/G212LFH-M2.csv
 - /hpc/scratch/hdd3/jz601442/datasets/squelette/2021-06/hk539925/ELN27012/control_csvs/G212LFN-M1.csv
plate_barcodes:
 - ELN27012_G212LFI
 - ELN27012_G212LFO
 - ELN27012_G212LFH
 - ELN27012_G212LFN
id_barcodes: 
 - ELN27012_G212LFI
 - ELN27012_G212LFO
m2_barcodes: 
 - ELN27012_G212LFI
 - ELN27012_G212LFH
save_path: /hpc/mydata/upt/cjh86475/channel_agnostic_model/finetuning/head_only/fvit
last_layer: head.module
plot_compounds: 
 - pos-M1
 - neg
 - pos-M2
vmin: 0.7
vmax: 1.0
controls: [
    ["pos-M1", "neg-M1"],
    ["pos-M2", "neg-M2"],
    ["pos-M1", "neg-M2"],
    ["pos-M2", "neg-M1"],
    ["pos-M1", "pos-M2"],
    ["neg-M1", "neg-M2"],
    ["neg-M1", "pos-M1"],
    ["neg-M2", "pos-M2"],
    ["neg-M2", "pos-M1"],
    ["neg-M1", "pos-M2"],
    ["pos-M2", "pos-M1"],
    ["neg-M2", "neg-M1"],
]
zprime_compounds: [
    "pos-M1",
    "pos-M2",
    "neg-M1",
    "neg-M2",
]
m2_plates:
 - ELN27012_G212LFH
 - ELN27012_G212LFI
