

comparison_model_name: 'MAE'

#FViT-s3
seed: 100
last_layer: 'encoder.head'
num_samples: 30
num_folds: 5
batch_size: 32
iid_split: test_out_compound
ood_split: test_out_all_
model_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/featurisation/nucleus_mitochondria/
controls_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/'
eval_data_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/'
eval_data_file_name: held_out_compounds_data
num_epochs: 100
log_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/lightning_logs/'
metrics_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/
patience: 25
model_name: mae
plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/channel_integration/nucleus_mitochondria/'


# control_ids: 


control_ids: ['2022_033924',
    '2022_085227',
    '2022_037716',
    '2022_025848',
    '2022_046054',
    '2022_035095',
    '2022_064022',
    '2022_050797',
    '2022_012818']


held_out_compounds_test_metric_dirs:
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/held_out_compound_test_metrics_dino_vits8_imagenet.pkl'
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/held_out_compound_test_metrics_mae.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/held_out_compound_test_metrics_mae.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/held_out_compound_test_metrics_dinov2_vitl14.pkl'

held_out_compounds_test_out_metric_dirs:
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/held_out_compound_test_ood_metrics_dino_vits8_imagenet.pkl'
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/held_out_compound_test_ood_metrics_mae.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/held_out_compound_test_ood_metrics_mae.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/held_out_compound_test_ood_metrics_dinov2_vitl14.pkl'

held_out_compounds_model_names: 
- DinoViT-S8
- MAE
- 'MAE (All source 3)'
- DinoViT-L14

held_out_compounds_plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/held_out_compound/'