
# Dinov2-ViT L14
# seed: 100
# last_layer: 'backbone.aggregate'
# num_samples: 30
# num_folds: 5
# batch_size: 32
# iid_split: test_out_compound
# ood_split: test_out_all_
# model_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/featurisation/dinov2_vitl14/
# controls_dir: /hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/
# eval_data_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/
# eval_data_file_name: held_out_aggregate_data
# num_epochs: 100
# log_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/lightning_logs/
# metrics_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/
# patience: 25
# model_name: dinov2_vitl14
# plot_save_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/


#DINOViT- s8
# seed: 100
# last_layer: 'backbone.aggregate'
# num_samples: 30
# num_folds: 5
# batch_size: 32
# iid_split: test_out_compound
# ood_split: test_out_all_
# model_dir: /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/jump_featurization/models/dino_vits8_imagenet/
# controls_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/'
# eval_data_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/'
# eval_data_file_name: held_out_aggregate_data
# num_epochs: 100
# log_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/lightning_logs/'
# metrics_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/
# patience: 25
# model_name: dino_vits8_imagenet
# plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/'


#FViT-S3 
seed: 100
last_layer: 'encoder.head'
num_samples: 30
num_folds: 5
batch_size: 32
iid_split: test_out_compound
ood_split: test_out_all_
model_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/featurisation/source3_rope/
controls_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/'
eval_data_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/'
eval_data_file_name: held_out_aggregate_data
num_epochs: 100
log_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/lightning_logs/'
metrics_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/
patience: 25
model_name: mae
plot_save_dir: '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/'



comparison_model_name: 'MAE'



control_ids: ['2022_033924',
    '2022_085227',
    '2022_037716',
    '2022_025848',
    '2022_046054',
    '2022_035095',
    '2022_064022',
    '2022_050797',
    '2022_012818']


held_out_compounds_test_metric_dirs:
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/nn_iid_accuracy_mae.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/nn_iid_accuracy_dinov2_vitl14.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/nn_iid_accuracy_dino_vits8_imagenet.pkl'
held_out_compounds_test_out_metric_dirs:
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/fvit_s3_rope/nn_ood_accuracy_mae.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dinov2_vitl14/nn_ood_accuracy_dinov2_vitl14.pkl'
- '/hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/dino_vits8_imagenet/nn_ood_accuracy_dino_vits8_imagenet.pkl'
held_out_compounds_model_names: 
- MAE
- Dino-L14
- Dino-S8

held_out_compounds_plot_save_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/model_evaluation/held_out_compound/well_level/