

seed: 100
last_layer: 'encoder.head'
num_samples: 30
num_folds: 5
batch_size: 32
model_dir: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/featurisation/scaled_source3_model/
controls_dir: '/hpc/scratch/nvme1/jz601442/jump_cp/controls_csv/source3_scaling/'
eval_data_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/scale_ctrls_source3/'
eval_data_file_name: held_out_compounds_data
num_epochs: 100
log_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/scale_ctrls_source3/lightning_logs/'
metrics_dir: /hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/scale_ctrls_source3/
patience: 25
model_name: mae
plot_save_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/scale_ctrls_source3/'

comparison_model_name: 'MAE'

# seed: 100
# last_layer: 'backbone.aggregate'
# num_samples: 30
# num_folds: 5
# batch_size: 32
# model_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/jump_featurization/models/dino_vits8_imagenet/'
# controls_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/controls/jump/source3/'
# eval_data_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/'
# # eval_data_file_name: held_out_compounds_data
# eval_data_file_name: small_held_out
# num_epochs: 100
# log_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/lightning_logs/'
# metrics_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/'
# patience: 25
# model_name: dino_vits8_imagenet
# plot_save_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/'


# control_ids: 


control_ids: ['2022_033924',
    '2022_085227',
    '2022_037716',
    '2022_025848',
    '2022_046054',
    '2022_035095',
    '2022_064022',
    '2022_050797',
    '2022_012818']


held_out_compounds_test_metric_dirs:
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/held_out_compound_test_metrics_dino_vits8_imagenet.pkl'
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/held_out_compound_test_metrics_mae.pkl'
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/source3_model/held_out_compound_test_metrics_mae.pkl'

held_out_compounds_test_out_metric_dirs:
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/dino_vits8_imagenet/held_out_compound_test_ood_metrics_dino_vits8_imagenet.pkl'
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/channel_integration/3_channels/held_out_compound_test_ood_metrics_mae.pkl'
- '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/source3_model/held_out_compound_test_ood_metrics_mae.pkl'

held_out_compounds_model_names: 
- DinoViT
- MAE
- 'MAE (All source 3)'

held_out_compounds_plot_save_dir: '/hdd_scratch2/cjh86475/channel_agnostic_model/experiment_outputs/model_evaluations/new/held_out_compound/'