seed: 10

plate_dir: /hpc/scratch/hdd4/cjh86475/small_data/jump/plate.csv
well_dir: /hpc/scratch/hdd4/cjh86475/small_data/jump/well.csv
compound_dir: /hpc/scratch/hdd4/cjh86475/small_data/jump/compound.csv
control_csv_path: /hpc/scratch/weka01/cjh86475/channel_agnostic_model/controls/source3/


num_compounds_held_out: 60
frac_compound_wells_in_train: 0.6


hold_out_target_plates: ['JCPQC051','JCPQC052','JCPQC053','JCPQC054','JCPQC034']
control_list: [
    'JCP2022_033924',
    'JCP2022_085227',
    'JCP2022_037716',
    'JCP2022_025848',
    'JCP2022_046054',
    'JCP2022_035095',
    'JCP2022_064022',
    'JCP2022_050797',
    'JCP2022_012818'
]

